version: '3'

services:
  blog:
    container_name: blog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:4000"
    expose:
      - 4000
    working_dir: /blog
    command: hexo server
